version: "3"

services:
  redis:
    image: "redis"
    ports:
      - 6379:6379
    expose:
      - 6379
    working_dir: /data
    environment:
      - REDIS_REPLICATION_MODE=master
    volumes:
      - redis_data_container:/data
volumes:
  redis_data_container:
    driver: local
